- libnacl/__init__.py
> fix generichash not working  32bit python windows.

- libnacl/base.py
- libnacl/utils.py
- tests/unit/test_save.py
To address concerns in issue #40 
By using `json.load` instead of `json.loads()` it might be possible to read from a stream, without affecting whatever may be next in the stream.
Enables support for `for_json()` feature of SimpleJSON
> Add support for reading/writing from JSON streams (also msgpack)

- libnacl/__init__.py
In some cases, especially when a custom Python is built, libnacl has trouble finding libsodium.  Currently libnacl looks first in the system's dynamic library path, then in /usr/local/lib, but errors out if it doesn't find it there.
If Python and dependencies are built and installed in an isolated directory tree, it's likely that that tree looks something like
```
/opt/python
/opt/python/lib
/opt/python/bin
```
etc.
and in this case libsodium probably will be in
```
/opt/python/lib/libsodium.so
```
and libnacl would be in
```
/opt/python/lib/site-packages/libnacl
```
So we'll just look for the 'lib' directory closest to the root and check in there as well as checking the other places for a libsodium.
> Have libnacl look for libsodium in the nearest `lib` directory to where libnacl itself is installed

- tests/unit/test_auth_verify.py
```
>>> crypto_onetimeauth_verify(crypto_onetimeauth('yolo', 'secret'), 'yolo', 'secret')
'yolo'
>>>
>>> crypto_onetimeauth_verify(crypto_onetimeauth('yolo', 'forged'), 'yolo', 'secret')
'yolo'
>>>
```
https://gist.github.com/kpcyrd/1ec95f93b1b13f6af35c
> Add regressiontest for crypto_onetimeauth_verify

- README.rst
- doc/topics/releases/1.0.0.rst
- libnacl/__init__.py
- pkg/rpm/python-libnacl.spec
- pkg/suse/python-libnacl.spec
- setup.py
tweetnacl's is a very limited subset of libsodium API. By dropping it we can implement support for all the missing libsodium and maintaining consistency between installations.
> remove one tweetnacl support - it is a small subset of the libsodium API

- setup.py
It's very hard to use modern Python without setuptools.
> use setuptools again - pip requires it anyhow.

- libnacl/__init__.py
- tests/unit/test_auth_verify.py
* add check parameters + tests
* fix test where the wrong key length was used
* add primitive identification function
> crypto_onetimeauth:

- libnacl/__init__.py
Debian testing and unstable and Ubuntu Xenial are shipping it already,
so libnacl breaks there.
> Add 18 to __SONAMES

- pkg/rpm/python-libnacl.spec
libnacl-1.4.4 doesn't work with libsodium-0.4.5-3.el6.x86_64 (latest version from CentOS EPEL)
> Addressing Issue #76 of saltstack/libnacl

- libnacl/__init__.py
- tests/unit/test_verify.py
I've discovered that libsodium has a function to compare two byte sequences with one another in constant time and I require such a function in my project (I know that there are other packages providing this but I want to keep dependencies at a minimum).
Disclaimer: I'm not a cryptologist, so I'm not sure about the length comparison. However, the `cryptography` project [does the same](https://cryptography.io/en/latest/_modules/cryptography/hazmat/primitives/constant_time/#bytes_eq) although [they compare the length in the C function](https://github.com/pyca/cryptography/blob/68b3b1ea8661b98c7afc3243e84c998601b70f18/src/_cffi_src/hazmat_src/constant_time.c) which puzzles me a bit.
> Add 'bytes_eq' function

- libnacl/public.py
PublicKey accepts any key length without checking. We were bitten by this today, we passed in a base64 encoded key and PublicKey didn't complain but of course calculating a shared secret resulted in a different one.
SecretKey checks the key length, so there's no reason for PublicKey to not do so as well.
> check public key length

- libnacl/__init__.py
I found a hard to trace bug in my application that when I passed `str` objects to `SealedBox.encrypt`, it encrypt just fine. However, it seems that the resulting box is truncated.
After some investigation I found that the allocated ctypes buffer is too small, as `len(msg)` measure the string length, not bytes.
This patch added a check that prevent passing non-bytes object to `crypto_box_seal` and `crypto_box_seal_open`.
> Check that arguments to crypto_box_seal/seal_open must be bytes

- libnacl/__init__.py
`crypto_box_SEEDBYTES` is missing. 
This PR adds this value by getting it directly from nacl.
> Adding crypto_box_seedbytes value and crypto_box_seed_keypair functionality

- libnacl/__init__.py
* crypto_box_open_afternm
* crypto_box_afternm
Fixes #74
> Fix inconsistency in exceptions raised.

- doc/topics/releases/1.5.1.rst
As already mentioned in https://github.com/saltstack/libnacl/pull/91#issuecomment-317757117.
The change in #91 is a breaking change for all applications that rely on catching encryption / decryption failures. Therefore it's important to mention it in the release notes.
The change could have been made reverse compatible by making `CryptError` a subclass of `ValueError`.
Do you have a policy regarding [semantic versioning](http://semver.org/)?
> Mention exception change in 1.5.1 release notes

- libnacl/__init__.py
- tests/unit/test_aead.py
The crypto_aead_aes256gcm_* functions are only implemented on certain
CPUs, so check whether they're available before trying to use them.
For good measure, also raise a nicer error if
crypto_aead_chacha20poly1305_ietf_* aren't available.
Fixes https://bugs.debian.org/869241.
> Check whether AEAD functions are available

- libnacl/__init__.py
`crypto_aead_aes256gcm_KEYBYTES`, `crypto_aead_aes256gcm_NPUBBYTES`, and
`crypto_aead_aes256gcm_ABYTES` should still be available even if CPU
support for AES256-GCM encryption/decryption is missing.
`libnacl.utils.aead_key` relies on this, and is needed by the
`test_ietf_aead` test which is run even without CPU support for
AES256-GCM.
> Restore crypto_aead_aes256gcm_*BYTES on old CPUs

- MANIFEST.in
PyPI tarball for 1.6.1 contains lots of .pyc files from author's install. This causes problems. Tweak MANIFEST.in entry for future release to only include .py files to help prevent a recurrence.
Fixes #112
> Tweak MANIFEST.in to include only .py files

- tests/unit/test_verify.py
In https://bugs.debian.org/922259, Santiago Vila reported that the
verify tests occasionally fail like this:
Traceback (most recent call last):
File "tests/unit/test_verify.py", line 30, in test_verify32
v32x[libnacl.randombytes_random() & 31] += 1
ValueError: byte must be in range(0, 256)
And indeed you can reproduce this by just running those tests in a loop
(e.g. `while python -m unittest discover --start-directory tests -v -p
test_verify.py; do :; done`).
This happens in the corner case where the previous value of the byte
that the test tries to increment happens to be 255; in that case it will
effectively try to assign 256 to a bytearray element and fail.  We can
fix this by explicitly folding the value back into the range of a byte.
> Fix unreliability in verify tests

- libnacl/__init__.py
To match crypto_kx_client_session_keys, it should have been returning
`rx.raw` and `tx.raw` rather than `rx` and `tx`.
This caused tests to fail in the 1.7 release, like this:
Traceback (most recent call last):
File "tests/unit/test_raw_random.py", line 103, in test_crypto_kx_server_session_keys
self.assertEqual(rx, rx2)
AssertionError: <ctypes.c_char_Array_32 object at 0x7f73114d6c20> != <ctypes.c_char_Array_32 object at 0x7f73116c6290>
> Fix crypto_kx_server_session_keys

- .travis.yml
`pypy2.7-6.0` is not available `pypy2` is now on ubuntu18.
> Fix pypy tests on travis

- libnacl/utils.py
> Remove encoding parameter json.loads for Python 3.9 compatibility.

- libnacl/public.py
Two instances of the same public/private key should be equal when compared, shouldn't they?
> Basic functions for equal-comparision and hashing of Keys.

- libnacl/__init__.py
In MacOS, the environment variable DYLD_LIBRARY_PATH is used to specify the search path for .dylibs ([manpage](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/dlopen.3.html)) . However that path is not utilized by the call to ctypes.cdll.LoadLibrary. The ctypes module provides a function intended specifically to take a base library name and try to map it to a file path: ctypes.util.find_library. This change simply tries that mechanism first to locate the libsodium shared library.
> try ctypes.util.find_library first to locate libsodium

- pyproject.toml
- fix the `include` entry for tests to name the correct directory
- include documentation sources as well, to permit building offline docs
> Fix installing tests in sdist, and include doc sources as well
